### ISSUE TITLE
Connection Failure with ZKTeco F16 Device Across All Protocols

### ISSUE THREAD

**Issue by yassine-fy94** [OmarHossamEldin/Dot-Env-Loader#1]
Hello, im sorry to write this comment on this project, i want to know if you have solved the issue with the zkteco F16

**Comment by OmarHossamEldin** [comment]
i made a temporary solution and after that, I got Raspberry Pi and did the entire solution with PHP and Raspberry Pi

**Comment by OmarHossamEldin** [comment]
@yassine-fy94 what is ur use case in general?

**Comment by yassine-fy94** [comment]
Thank you for your response sir, i have been using pyzk to establish a connection with ZKTECO devices(mb360-IN01-MA300 etc..) and sending whatever commands we'd like, get data, add user/ delete user ... etc, but the ZKTECO F16 ( Firmware Version : Ver 6.64.0013 Oct 16 2018 ), its i not supported by pyzk, or any known opensource library, it works only with the desktop application ZKAccess3.5 Security System, and the web app ZKBio Access IVS, and both they couldnt be used as api or to be integrated on my ERP, is your solution compatible with the Firmware Version : Ver 6.64.0013 Oct 16 2018, if so is it open source or we could negotiate a colaboration ? @OmarHossamEldin.

**Comment by OmarHossamEldin** [comment]
is see but the answer to u is do it with Raspberry Pi because I will give u more control and can do whatever u want bc zk devices have a lot of limitations tbh and if u are asking for a opensource solution I can pick this library [cobisja/tad-php](https://github.com/cobisja/tad-php) and tell me if u meet any problems

**Comment by yassine-fy94** [comment]
Thank you sir for your response, i have tried to use tad-php but unfortunately it is deprecated, even so have upgraded it to php 8, but still no result with the device, is there any other solution to communicate with the Firmware Version : Ver 6.64.0013 ?

**Comment by OmarHossamEldin** [comment]
@yassine-fy94  my case i sloved it using sql server and connect to it with its app as temp as i told u 
so i used Raspberry Pi because It will give u more control and can do whatever u want bc zk devices have a lot of limitations tbh as i said before
